# Mandatory settings
name: Sebastian Schmidt
paginate: 25
paginate_path: "/blog/posts/page/:num/"
url: https://sebastian-schmidt.me
canonical: https://sebastian-schmidt.me
blog_theme: light # Or dark

# Optional settings
livereload: false # browser auto-reload for development
discus_identifier: # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
piwik: # Add your Piwik Tracking Id
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  github: publicarray # Add your GitHub handle
  linkedin: publicarray # Add your LinkedIn handle
  twitter: publicarray # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  keybase: publicarray
  tox: publicarray

# https://github.com/jekyll/jekyll-assets/wiki/Configuration
assets:
  cache_type: memory
  compress:
    css: true
    js: true
  autoprefixer:
    browsers:
      - "> 0.5%"
      - "last 2 versions"
      - "IE > 9"
  sources:
    - node_modules
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  features:
    automatic_img_size: true
    automatic_img_alt: true

# Important settings (change at own risk)
collections:
  my_tags:
    output: true
    permalink: /blog/tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - node_modules/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: blog/posts/:slug/
