version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: rails-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: rails-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: Test with htmlproofer
          command: |
            bundle exec htmlproofer ./_site \
              --only-4xx \
              --allow-hash-href \
              --assume-extension \
              --check-opengraph \
              --url-ignore "feed.xml" \
              --url-ignore "/\.\//"
          #   --check-img-http \
          #   --check-html \
          #   --report-invalid-tags \
          #   --report-missing-names \
          #   --report-missing-doctype
          # wait for https://github.com/gjtorikian/html-proofer/pull/362
